export const mockProducts = [
  {
    id: 1,
    name: 'Cat With Knife "WHAT?" Hoodie',
    image: '/hoodie1.png',
    price: 34.99,
    oldPrice: 49.99,
    rating: 4.5,
  },
  {
    id: 2,
    name: 'Scooby-Doo Black Hoodie',
    image: '/hoodie2.png',
    price: 29.99,
    rating: 4,
  },
  {
    id: 3,
    name: '"TEACHER" Navy Hoodie',
    image: '/hoodie3.png',
    price: 27.99,
    oldPrice: 39.99,
    rating: 5,
  },
  {
    id: 4,
    name: 'Frieren Anime Gray Hoodie',
    image: '/hoodie4.png',
    price: 32.99,
    rating: 3.5,
  },
  {
    id: 5,
    name: 'One Piece Sunset Sweatshirt',
    image: '/hoodie5.png',
    price: 39.99,
    oldPrice: 54.99,
    rating: 4,
  },
  {
    id: 6,
    name: 'Cat Stack Black Hoodie',
    image: '/hoodie6.png',
    price: 31.99,
    rating: 4.5,
  },
  {
    id: 7,
    name: 'Onizuka GTO Anime Hoodie',
    image: '/hoodie7.png',
    price: 36.99,
    oldPrice: 44.99,
    rating: 4,
  },
  {
    id: 8,
    name: 'Zero Two Darling Hoodie',
    image: '/hoodie8.png',
    price: 37.99,
    rating: 4.5,
  },
  {
    id: 9,
    name: 'Cute Cats Love Hoodie',
    image: '/hoodie9.png',
    price: 28.99,
    oldPrice: 38.99,
    rating: 5,
  },
  {
    id: 10,
    name: 'Ork WAAAGH! Navy Hoodie',
    image: '/hoodie10.png',
    price: 33.99,
    rating: 3.5,
  },
  {
    id: 11,
    name: 'Temmie Undertale Red Hoodie',
    image: '/hoodie11.png',
    price: 29.99,
    oldPrice: 39.99,
    rating: 4,
  },
  {
    id: 12,
    name: 'XX Smiley Face Red Hoodie',
    image: '/hoodie12.png',
    price: 25.99,
    rating: 4.5,
  },
  {
    id: 13,
    name: 'Samurai Cat Red Sweatshirt',
    image: '/hoodie13.png',
    price: 35.99,
    rating: 4,
  },
  {
    id: 14,
    name: 'Letter "M" Red Hoodie',
    image: '/hoodie14.png',
    price: 24.99,
    oldPrice: 34.99,
    rating: 5,
  },
  {
    id: 15,
    name: 'Cat Silhouette Black Hoodie',
    image: '/hoodie15.png',
    price: 27.99,
    rating: 3.5,
  },
  {
    id: 16,
    name: '"This Is Fine" Meme Hoodie',
    image: '/hoodie16.png',
    price: 34.99,
    oldPrice: 46.99,
    rating: 4.5,
  },
  {
    id: 17,
    name: 'Cat With Lemons Gray Hoodie',
    image: '/hoodie17.png',
    price: 29.99,
    rating: 4,
  },
  {
    id: 18,
    name: 'Killer Bunny Black Hoodie',
    image: '/hoodie18.png',
    price: 32.99,
    oldPrice: 42.99,
    rating: 4.5,
  },
  {
    id: 19,
    name: 'Goose HONK Black Hoodie',
    image: '/hoodie19.png',
    price: 28.99,
    rating: 3.5,
  },
  {
    id: 20,
    name: 'Evil Grin Black Hoodie',
    image: '/hoodie20.png',
    price: 31.99,
    oldPrice: 41.99,
    rating: 4,
  },
  {
    id: 21,
    name: 'DanDaDan Cat Sweatshirt',
    image: '/hoodie21.png',
    price: 36.99,
    rating: 4.5,
  },
  {
    id: 22,
    name: '"COFFEEEE" Bunny Navy Hoodie',
    image: '/hoodie22.png',
    price: 27.99,
    oldPrice: 37.99,
    rating: 5,
  },
  {
    id: 23,
    name: 'Yamete Kudasai Anime Hoodie',
    image: '/hoodie23.png',
    price: 33.99,
    rating: 4,
  },
  {
    id: 24,
    name: 'Swan Lake Ballet Hoodie',
    image: '/hoodie24.png',
    price: 30.99,
    oldPrice: 42.99,
    rating: 4.5,
  },
  {
    id: 25,
    name: 'SUDO Highway To Shell Hoodie',
    image: '/hoodie25.png',
    price: 29.99,
    rating: 4,
  },
  {
    id: 26,
    name: 'Pocket Cat Beige Sweatshirt',
    image: '/hoodie26.png',
    price: 34.99,
    oldPrice: 44.99,
    rating: 5,
  },
  {
    id: 27,
    name: 'The Offspring Navy Hoodie',
    image: '/hoodie27.png',
    price: 35.99,
    rating: 4.5,
  },
  {
    id: 28,
    name: 'Classic Black Blank Hoodie',
    image: '/hoodie28.png',
    price: 22.99,
    oldPrice: 29.99,
    rating: 4,
  },
  {
    id: 29,
    name: '"Ё Ма Ха" Mint Sweatshirt',
    image: '/hoodie29.png',
    price: 26.99,
    rating: 3.5,
  },
  {
    id: 30,
    name: 'One Piece Skull Brown Sweatshirt',
    image: '/hoodie30.png',
    price: 36.99,
    oldPrice: 48.99,
    rating: 5,
  },
];
